### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by dglazkov** [DevProgress/debate-bingo#33]
... So that we can track how popular the app is.

**Comment by jillh510** [comment]
Assigning to decause for now to get us a GA key

**Comment by jillh510** [comment]
Assuming we're going with GA, here's what I propose for custom events:

eventCategory: bingoCard
possible eventActions: create, bingo
possible eventLabels: hillary, trump

eventCategory: share (NB this will record clicks on a share button, not whether the user actually posted)
possible eventActions: share
possible eventLabels: twitter, facebook, google_plus, linked_in

Comments welcome
(9/24/2016: changed the event from "win" to "bingo" because I couldn't stand the idea of analytics events that said "win trump")

**Comment by decause** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83595614-4', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by jillh510** [comment]
Reopening to assign to myself.

**Comment by jillh510** [comment]
Update: events for card creation and bingo are in, pending merge of bug fix. Events for Share icons are harder and not blocking for v1.0. Taking the 1.0 label off of this issue.
